# Generated by Django 5.2.9 on 2025-12-02 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT Empresa')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_solicitada', models.DateField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, help_text='Presencial, Online, Mixta, etc.', max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('profesional_asignado', models.ForeignKey(blank=True, help_text='Profesional que atiende la clase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_asignadas', to=settings.AUTH_USER_MODEL)),
                ('solicitada_por', models.ForeignKey(blank=True, help_text='Usuario que crea la solicitud (cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=150)),
                ('registro_profesional', models.CharField(blank=True, max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=20, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente / Usuario'), ('PROFESIONAL', 'Profesional')], default='CLIENTE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
