# Generated by Django 5.2.9 on 2025-12-02 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ['user__username'], 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterField(
            model_name='clase',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='api.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_solicitada',
            field=models.DateField(blank=True, help_text='Fecha en que el cliente desea realizar la clase.', null=True, verbose_name='Fecha solicitada'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='modalidad',
            field=models.CharField(blank=True, help_text='Ej: Presencial, Online, Mixta, etc.', max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesional_asignado',
            field=models.ForeignKey(blank=True, help_text='Profesional responsable de esta clase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_asignadas', to='api.profesional', verbose_name='Profesional asignado'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='solicitada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registra esta solicitud en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitada por'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que gestiona este cliente en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Ej: Prevención de riesgos, Ergonomía, Seguridad industrial, etc.', max_length=150, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='registro_profesional',
            field=models.CharField(blank=True, help_text='Número de registro o certificación (si aplica).', max_length=50, verbose_name='Registro profesional'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente / Usuario'), ('PROFESIONAL', 'Profesional')], default='CLIENTE', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
