# Generated by Django 5.2.9 on 2025-12-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_clase_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente / Usuario'), ('PROFESIONAL', 'Profesional')], default='CLIENTE', help_text='Define el tipo de usuario dentro del sistema.', max_length=20, verbose_name='Rol'),
        ),
    ]
