# Generated by Django 5.2.9 on 2025-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_direccion_alter_userprofile_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='No Más Accidentes', max_length=150, verbose_name='Nombre del sistema')),
                ('razon_social', models.CharField(blank=True, help_text='Nombre legal de la empresa', max_length=200, verbose_name='Razón social')),
                ('rut_empresa', models.CharField(blank=True, max_length=20, verbose_name='RUT empresa')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('telefono_contacto', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('sitio_web', models.CharField(blank=True, max_length=200, verbose_name='Sitio web')),
                ('dias_min_anticipacion_cancelacion', models.PositiveIntegerField(default=2, help_text='Se puede usar como referencia al validar cancelaciones.', verbose_name='Días mínimos de anticipación para cancelar clase')),
                ('permitir_registro_publico_clientes', models.BooleanField(default=True, help_text='Si está en False, se podría bloquear el formulario /registro-cliente.', verbose_name='Permitir registro público de clientes')),
                ('texto_portada', models.CharField(blank=True, help_text='Texto corto para mostrar en la página de inicio.', max_length=255, verbose_name='Mensaje de portada')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
